export default {
    colors: {
        Gray: {
            colorName: [
                "GRAY 0",
                "GRAY 1",
                "GRAY 2",
                "GRAY 3",
                "GRAY 4",
                "GRAY 5",
                "GRAY 6",
                "GRAY 7",
                "GRAY 8",
                "GRAY 9",
            ],
            colorCode: [
                "#f8f9fa",
                "#f1f3f5",
                "#e9ecef",
                "#dee2e6",
                "#ced4da",
                "#adb5bd",
                "#868e96",
                "#495057",
                "#343a40",
                "#212529",
            ]
        },
        Red: {
            colorName: [
                "RED 0",
                "RED 1",
                "RED 2",
                "RED 3",
                "RED 4",
                "RED 5",
                "RED 6",
                "RED 7",
                "RED 8",
                "RED 9",
            ],
            colorCode: [
                "#fff5f5",
                "#ffe3e3",
                "#ffc9c9",
                "#ffa8a8",
                "#ff8787",
                "#ff6b6b",
                "#fa5252",
                "#f03e3e",
                "#e03131",
                "#c92a2a",
            ]
        },
        Pink: {
            colorName: [
                "PINK 0",
                "PINK 1",
                "PINK 2",
                "PINK 3",
                "PINK 4",
                "PINK 5",
                "PINK 6",
                "PINK 7",
                "PINK 8",
                "PINK 9",
            ],
            colorCode: [
                "#fff0f6",
                "#ffdeeb",
                "#fcc2d7",
                "#faa2c1",
                "#f783ac",
                "#f06595",
                "#e64980",
                "#d6336c",
                "#c2255c",
                "#a61e4d",
            ]
        },
        Grape: {
            colorName: [
                "GRAPE 0",
                "GRAPE 1",
                "GRAPE 2",
                "GRAPE 3",
                "GRAPE 4",
                "GRAPE 5",
                "GRAPE 6",
                "GRAPE 7",
                "GRAPE 8",
                "GRAPE 9",
            ],
            colorCode: [
                "#f8f0fc",
                "#f3d9fa",
                "#eebefa",
                "#e599f7",
                "#da77f2",
                "#cc5de8",
                "#be3bdb",
                "#ae3ec9",
                "#9c36b5",
                "#862e9c",
            ]
        },
        Violet: {
            colorName: [
                "VIOLET 0",
                "VIOLET 1",
                "VIOLET 2",
                "VIOLET 3",
                "VIOLET 4",
                "VIOLET 5",
                "VIOLET 6",
                "VIOLET 7",
                "VIOLET 8",
                "VIOLET 9",
            ],
            colorCode: [
                "#f3f0ff",
                "#e5dbff",
                "#d0bfff",
                "#b197fc",
                "#9775fa",
                "#845ef7",
                "#7950f2",
                "#7048e8",
                "#6741d9",
                "#5f3dc4",
            ]
        },
        Indigo: {
            colorName: [
                "INDIGO 0",
                "INDIGO 1",
                "INDIGO 2",
                "INDIGO 3",
                "INDIGO 4",
                "INDIGO 5",
                "INDIGO 6",
                "INDIGO 7",
                "INDIGO 8",
                "INDIGO 9",
            ],
            colorCode: [
                "#edf2ff",
                "#dbe4ff",
                "#bac8ff",
                "#91a7ff",
                "#748ffc",
                "#5c7cfa",
                "#4c6ef5",
                "#4263eb",
                "#3b5bdb",
                "#364fc7",
            ]
        },
        Blue: {
            colorName: [
                "BLUE 0",
                "BLUE 1",
                "BLUE 2",
                "BLUE 3",
                "BLUE 4",
                "BLUE 5",
                "BLUE 6",
                "BLUE 7",
                "BLUE 8",
                "BLUE 9",
            ],
            colorCode: [
                "#e7f5ff",
                "#d0ebff",
                "#a5d8ff",
                "#74c0fc",
                "#4dabf7",
                "#339af0",
                "#228be6",
                "#1c7ed6",
                "#1971c2",
                "#1864ab",
            ]
        },
        Cyan: {
            colorName: [
                "CYAN 0",
                "CYAN 1",
                "CYAN 2",
                "CYAN 3",
                "CYAN 4",
                "CYAN 5",
                "CYAN 6",
                "CYAN 7",
                "CYAN 8",
                "CYAN 9",
            ],
            colorCode: [
                "#e3fafc",
                "#c5f6fa",
                "#99e9f2",
                "#66d9e8",
                "#3bc9db",
                "#22b8cf",
                "#15aabf",
                "#1098ad",
                "#0c8599",
                "#0b7285",
            ]
        },
        Teal: {
            colorName: [
                "Teal 0",
                "Teal 1",
                "Teal 2",
                "Teal 3",
                "Teal 4",
                "Teal 5",
                "Teal 6",
                "Teal 7",
                "Teal 8",
                "Teal 9",
            ],
            colorCode: [
                "#e6fcf5",
                "#c3fae8",
                "#96f2d7",
                "#63e6be",
                "#38d9a9",
                "#20c997",
                "#12b886",
                "#0ca678",
                "#099268",
                "#087f5b",
            ]
        },
        Green: {
            colorName: [
                "GREEN 0",
                "GREEN 1",
                "GREEN 2",
                "GREEN 3",
                "GREEN 4",
                "GREEN 5",
                "GREEN 6",
                "GREEN 7",
                "GREEN 8",
                "GREEN 9",
            ],
            colorCode: [
                "#ebfbee",
                "#d3f9d8",
                "#b2f2bb",
                "#8ce99a",
                "#69db7c",
                "#51cf66",
                "#40c057",
                "#37b24d",
                "#2f9e44",
                "#2b8a3e",
            ]
        },
        Lime: {
            colorName: [
                "LIME 0",
                "LIME 1",
                "LIME 2",
                "LIME 3",
                "LIME 4",
                "LIME 5",
                "LIME 6",
                "LIME 7",
                "LIME 8",
                "LIME 9",
            ],
            colorCode: [
                "#f4fce3",
                "#e9fac8",
                "#d8f5a2",
                "#c0eb75",
                "#a9e34b",
                "#94d82d",
                "#82c91e",
                "#74b816",
                "#66a80f",
                "#5c940d",
            ]
        },
        Yellow: {
            colorName: [
                "YELLOW 0",
                "YELLOW 1",
                "YELLOW 2",
                "YELLOW 3",
                "YELLOW 4",
                "YELLOW 5",
                "YELLOW 6",
                "YELLOW 7",
                "YELLOW 8",
                "YELLOW 9",
            ],
            colorCode: [
                "#fff9db",
                "#fff3bf",
                "#ffec99",
                "#ffe066",
                "#ffd43b",
                "#fcc419",
                "#fab005",
                "#f59f00",
                "#f08c00",
                "#e67700",
            ]
        },
        Orange: {
            colorName: [
                "ORANGE 0",
                "ORANGE 1",
                "ORANGE 2",
                "ORANGE 3",
                "ORANGE 4",
                "ORANGE 5",
                "ORANGE 6",
                "ORANGE 7",
                "ORANGE 8",
                "ORANGE 9",
            ],
            colorCode: [
                "#fff4e6",
                "#ffe8cc",
                "#ffd8a8",
                "#ffc078",
                "#ffa94d",
                "#ff922b",
                "#fd7e14",
                "#f76707",
                "#e8590c",
                "#d9480f",
            ]
        }
    }
}